### ISSUE TITLE
How to styel Markdown Code 

### ISSUE THREAD

**Issue by zewditu** [Kryptos-FR/markdig.wpf#51] opened 2022-01-25 07:52 UTC
I have an issue theming for  code
  Markdig version : 0.5.0.1
VS version: 2022 preview 3.0;
![image](https://user-images.githubusercontent.com/36615490/150930139-94bdcd0c-9a61-4ca0-acec-f4778b17043c.png)

It seems that markdig  has  style for codes 
![image](https://user-images.githubusercontent.com/36615490/150929715-1a338dd4-fb67-40a0-9b63-c30cda3fe13e.png).

However, what target framework controls the style that should be applied? should it be applied to Textblock or something else?

**Comment by zewditu** [comment] 2022-01-25 08:02
I got it

**Comment by zewditu** [comment] 2022-01-25 08:19
I reopened it, I need to know for code blocks 
 ```` 
 Code block   
code block
 `````

**Comment by Kryptos-FR** [comment] 2022-01-25 19:33
Starting to look like a duplicate of #23, #24 and #30.

Styles can be overridden with the keys mentioned in your screenshot. There you can define text font, color as well as background color and any other style properties already supported by `Paragraph`.

**Comment by zewditu** [comment] 2022-01-28 20:03
Hi @Kryptos-FR nice `Paragraph` works fine for me.
I have one more question how writing code blocks with specific language colorization like csharp?


![image](https://user-images.githubusercontent.com/36615490/151617753-c5a7567d-5be9-4692-b41a-1c4692bf4032.png)


```csharp
public void MakeDeposit(decimal amount, DateTime date, string note)
{
}

public void MakeWithdrawal(decimal amount, DateTime date, string note)
{
}
```

**Comment by Kryptos-FR** [comment] 2022-01-29 11:10
@zewditu this is currently not supported.

It would require quite a lot of work to have different renderer strategies based on the language including parsing the text that goes inside a code block.

Currently this repository is in maintenance mode as I don't have time to work on new features. Contributions are welcomed.

**Closed as completed** 2022-06-23 18:29 UTC
