### ISSUE TITLE
How to change default fontfamily?

### ISSUE THREAD

**Issue by chenxuuu** [Kryptos-FR/markdig.wpf#30] opened 2019-08-14 14:30 UTC
default font is not right, how to change it?

**Comment by Kryptos-FR** [comment] 2019-08-14 15:29
You can override any style you want.

See https://github.com/Kryptos-FR/markdig.wpf/blob/develop/src/Markdig.Wpf/Themes/generic.xaml

----
Closed as duplicate of #23 and #24.

**Closed as completed by Kryptos-FR** 2019-08-14 15:29 UTC
Labels: question

**Comment by chenxuuu** [comment] 2019-08-15 00:38
I see
thanks!
